console.log("Site made by CodeHaven");

width = window.innerWidth;
console.log(width);

if (width <= 890) {
    console.log("Mobile activated");

    document.getElementById("home").innerHTML = "<div class='pf'><div class='pft'><h1>Océane Hair Studio</h1><div class='stars'><span class='gstar'>&#9733;</span><span class='gstar'>&#9733;</span><span class='gstar'>&#9733;</span><span class='gstar'>&#9733;</span><span class='gstar'>&#9733;</span></div><img class='pimg' src='salon.jpg' alt='salon photo'><div class='dets'><p>WOMEN - MEN - KIDS SERVICES</p><p>Hair cutting and styling <br> Colouring &amp; Keratin Treatment <br> Barber services</p><a class='pfta' target='_blank' href='https://www.fresha.com/a/oceane-hair-studio-killarney-heights-19-cashel-crescent-nb01ns6s/booking'>See all services and prices</a></div></div></div>";
    document.getElementById("ri").innerHTML = "<div id='carouselExampleIndicators' class='carousel slide' data-ride='carousel'><ol class='carousel-indicators'><li data-target='#carouselExampleIndicators' data-slide-to='0' class='active'></li><li data-target='#carouselExampleIndicators' data-slide-to='1'></li><li data-target='#carouselExampleIndicators' data-slide-to='2'></li><li data-target='#carouselExampleIndicators' data-slide-to='3'></li></ol><div class='carousel-inner'><div class='carousel-item active'><img class='d-block w-100' src='results1.jpg' alt='First slide'></div><div class='carousel-item'><img class='d-block w-100' src='results2.jpg' alt='Second slide'></div><div class='carousel-item'><img class='d-block w-100' src='results3.jpg' alt='Third slide'></div><div class='carousel-item'><img class='d-block w-100' src='results4.jpg' alt='Fourth slide'></div></div><a class='carousel-control-prev' href='#carouselExampleIndicators' role='button' data-slide='prev'><span class='carousel-control-prev-icon' aria-hidden='true'></span><span class='sr-only'>Previous</span></a><a class='carousel-control-next' href='#carouselExampleIndicators' role='button' data-slide='next'><span class='carousel-control-next-icon' aria-hidden='true'></span><span class='sr-only'>Next</span></a></div>";
    document.getElementById("oky").innerHTML = "<div class='reviews' id='Reviews'><h2>Reviews</h2><div id='carouselExampleCaptions' class='carousel slide'><div class='carousel-indicators'><button type='button' data-bs-target='#carouselExampleCaptions' data-bs-slide-to='0' class='active' aria-current='true' aria-label='Slide 1'></button><button type='button' data-bs-target='#carouselExampleCaptions' data-bs-slide-to='1' aria-label='Slide 2'></button><button type='button' data-bs-target='#carouselExampleCaptions' data-bs-slide-to='2' aria-label='Slide 3'></button><button type='button' data-bs-target='#carouselExampleCaptions' data-bs-slide-to='3' aria-label='Slide 4'></button><button type='button' data-bs-target='#carouselExampleCaptions' data-bs-slide-to='4' aria-label='Slide 5'></button></div><div class='carousel-inner'><div class='carousel-item active' id='c1'><div class='carousel-caption d-none d-md-block'></div></div><div class='carousel-item' id='c2'><div class='carousel-caption d-none d-md-block'></div></div><div class='carousel-item' id='c3'><div class='carousel-caption d-none d-md-block'></div></div><div class='carousel-item' id='c4'><div class='carousel-caption d-none d-md-block'></div></div><div class='carousel-item' id='c5'><div class='carousel-caption d-none d-md-block'></div></div></div><button class='carousel-control-prev' type='button' data-bs-target='#carouselExampleCaptions' data-bs-slide='prev'><span class='carousel-control-prev-icon' aria-hidden='true'></span><span class='visually-hidden'>Previous</span></button><button class='carousel-control-next' type='button' data-bs-target='#carouselExampleCaptions' data-bs-slide='next'><span class='carousel-control-next-icon' aria-hidden='true'></span><span class='visually-hidden'>Next</span></button></div><button class='btn-rr' onclick='show()'>View All</button><div id='s' class='show-div'><button class='s-close material-symbols-outlined' onclick='idkwhat()'>close</button><div id='rr' class='r-r'><h2>Reviews</h2></div></div></div>";
    document.getElementById("c1").innerHTML = "<div class='rit'><h4>Bodhi S.</h4><p>16 Feb 2024</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Oceane was amazing! Her foils and colour are beautiful. Very happy with the end result :)</p>";
    document.getElementById("c2").innerHTML = "<div class='rit'><h4>Siobhan W.</h4><p>12 June 2024</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Having my hair cut by Oceane is always a great experience. She is a fantastic stylist. Her studio is very peaceful.</p>";
    document.getElementById("c3").innerHTML = "<div class='rit'><h4>Aurelia F.</h4><p>2 May 2024</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Amazing! Love the result and my hair loves it too! Océane is always spot on for beautiful healthy natural results!!!!</p>";
    document.getElementById("c4").innerHTML = "<div class='rit'><h4>Gina M.</h4><p>9 Apr 2024</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Excellent cuts and such a lovely person. Highly recommend.</p>";
    document.getElementById("c5").innerHTML = "<div class='rit'><h4>Megan J.</h4><p>1 Feb 2024</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>I loved the relaxed atmosphere of the salon, but mostly I loved that Océane understood what I was asking for (in spite of my confusing instructions) and actually achieved it! Merci!!</p>";
    document.getElementById("rr").innerHTML = "<div class='kys'><h2>Reviews</h2><div id='e1'></div><div id='e2'></div><div id='e3'></div><div id='e4'></div><div id='e5'></div><div id='e6'></div><div id='e7'></div><div id='e8'></div><div id='e9'></div></div>";
    document.getElementById("e1").innerHTML = "<div class='ri mm'><div class='rit'><h4>Bodhi S.</h4><p>16 feb 2024</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Oceane was amazing! Her foils and colour are beautiful. Very happy with the end result :)</p></div><div class='ri mm'><div class='rit'><h4>Siobhan W.</h4><p>12 June 2024</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Having my hair cut by Oceane is always a great experience. She is a fantastic stylist. Her studio is very peaceful.</p></div><div class='ri mm'><div class='rit'><h4>Aurelia F.</h4><p>2 May 2024</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Amazing! Love the result and my hair loves it too! Océane is always spot on for beautiful healthy natural results!!!!</p></div><div class='ri mm'><div class='rit'><h4>Joanne Y.</h4><p>13 Apr 2024</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>On time! So friendly, did exactly what i asked for. Will def be back! I found my new hairdresser!</p></div>";
    document.getElementById("e2").innerHTML = "<div class='ri mm'><div class='rit'><h4>Gina M.</h4><p>9 Apr 2024</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Excellent cuts and such a lovely person. Highly recommend.</p></div><div class='ri mm'><div class='rit'><h4>Megan J.</h4><p>1 Feb 2024</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>I loved the relaxed atmosphere of the salon, but mostly I loved that Océane understood what I was asking for (in spite of my confusing instructions) and actually achieved it! Merci!!</p></div><div class='ri mm'><div class='rit'><h4>Xenia E.</h4><p>27 June 2024</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Oceane is amazing. Today she went above and beyond with a new keratin product that I asked for. She went out of her way to get it and did the treatment perfectly. The salon is so peaceful and calming which makes it a pleasure to get my hair done. Highly recommend Oceane hair studio.</p></div><div class='ri mm'><div class='rit'><h4>Axel S.</h4><p>22 June 2024</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Top! As usual!</p></div><div class='ri mm'><div class='rit'><h4>Rob L.</h4><p>22 June 2024</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Great!</p></div>";
    document.getElementById("e3").innerHTML = "<div class='ri mm'><div class='rit'><h4>Marianne A.</h4><p>12 Apr 2024</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Super!</p></div><div class='ri mm'><div class='rit'><h4>Frederic B.</h4><p>12 Apr 2024</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Amazing service and great time as usual</p></div><div class='ri mm'><div class='rit'><h4>Nadine H.</h4><p>9 Mar 2024</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Océane is the best! Such an enjoyable experience</p></div><div class='ri mm'><div class='rit'><h4>David O.</h4><p>25 Feb 2024</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Great Haircut</p></div>";
    document.getElementById("e4").innerHTML = "<div class='ri mm'><div class='rit'><h4>Yoann S.</h4><p>20 Feb 2024</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Great</p></div><div class='ri mm'><div class='rit'><h4>Angela F.</h4><p>2 Feb 2024</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Lovely spot and a great hair cut. Thank you.</p></div><div class='ri mm'><div class='rit'><h4>Angela F.</h4><p>2 Feb 2024</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Lovely spot and a great hair cut. Thank you.</p></div><div class='ri mm'><div class='rit'><h4>Daniele D.</h4><p>17 Jan 2024</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Love the products and the service!</p></div>";
    document.getElementById("e5").innerHTML = "<div class='ri mm'><div class='rit'><h4>Angela</h4><p>16 Dec 2023</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Océane is the best hairdresser! She is an expert in hairdressing. I had a colour and blow dry today and my hair looks amazing- I absolutely love it! I can’t wait to go back again in a few weeks. Thank you again Océane</p></div><div class='ri mm'><div class='rit'><h4>Rob L.</h4><p>15 Nov 2023</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Great!</p></div><div class='ri mm'><div class='rit'><h4>Sophie C.</h4><p>14 Nov 2023</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Lovely time spent with Océane.</p></div><div class='ri mm'><div class='rit'><h4>Rod</h4><p>3 Nov 2023</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Friendly. Always a great cut, so always walk out happy. And, Ocean uses organic products which is even better. Cest magnifique :)</p></div>";
    document.getElementById("e6").innerHTML = "<div class='ri mm'><div class='rit'><h4>Noemi B.</h4><p>31 Oct 2023</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>great colour!</p></div><div class='ri mm'><div class='rit'><h4>Coralie A.</h4><p>28 Oct 2023</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Océane is a great hairdresser and a beautiful person too! I love her hair cuts and her kindness. Spending an hour in her hands definitely makes you feel and look good!</p></div><div class='ri mm'><div class='rit'><h4>Clem</h4><p>13 Oct 2023</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Punctual, attentive to client’s needs, efficient and super friendly.. Oceane is a gem!</p></div><div class='ri mm'><div class='rit'><h4>Anne B.</h4><p>6 Oct 2023</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Top coiffeuse !</p></div>";
    document.getElementById("e7").innerHTML = "<div class='ri mm'><div class='rit'><h4>Rod</h4><p>6 Oct 2023</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Ocean makes you feel at home, and always delivers a great cut.</p></div><div class='ri mm'><div class='rit'><h4>Jenny D.</h4><p>2 Sept 2023</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>The best bio hair dye! Smells amazing and I always love the colour.</p></div><div class='ri mm'><div class='rit'><h4>Balazs K.</h4><p>2 Sept 2023</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Yeah best cut for Hudson</p></div><div class='ri mm'><div class='rit'><h4>Nadine H.</h4><p>26 Aug 2023</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>I always feel a million dollars after visiting Oceane.. she’s fantastic - 100% recommend her services!</p></div>";
    document.getElementById("e8").innerHTML = "<div class='ri mm'><div class='rit'><h4>Chris T.</h4><p>20 Aug 2023</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>I’ve been going to Océane for more than 6 years, she has to be the best hair cutter on the north shore.</p></div><div class='ri mm'><div class='rit'><h4>Roni M.</h4><p>9 Aug 2023</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Just fabulous in all ways xx</p></div><div class='ri mm'><div class='rit'><h4>Manuela S.</h4><p>22 July 2023</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>The best hairdresser! I always walk out feeling beautiful and I love that the products used don’t harm my health or my hair.</p></div><div class='ri mm'><div class='rit'><h4>Clem</h4><p>21 July 2023</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Great experience at Oceane’s studio. Very professional and attentive to the customer’s needs, highly recommend. Great with curly hair too! :)</p></div><div class='ri mm'><div class='rit'><h4>Sholeen C.</h4><p>19 July 2023</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Océane is an amazing hairdresser who was very interested in understanding my needs regarding the colour I wanted. Thank you for an amazing hairdressing experience today! My hair colour is fantastic and I did not experience any discomfit during the entire time the colour stayed on my hair. My hair feels lovely and soft with No residual itching or irritation post colouring. See you again in a few weeks </p></div>";
    document.getElementById("e9").innerHTML = "<div class='ri horizontal-scroll'><div class='rit'><h4>Axel S.</h4><p>22 June 2024</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Top! As usual!</p></div><div class='ri horizontal-scroll'><div class='rit'><h4>Xenia E.</h4><p>27 June 2024</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Oceane is amazing. Today she went above and beyond with a new keratin product that I asked for. She went out of her way to get it and did the treatment perfectly. The salon is so peaceful and calming which makes it a pleasure to get my hair done. Highly recommend Oceane hair studio.</p></div><div class='ri horizontal-scroll'><div class='rit'><h4>Roni M.</h4><p>29 June 2024</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Love your work, always.</p></div><div class='ri horizontal-scroll'><div class='rit'><h4>Madeline D.</h4><p>17 July 2024</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Beautiful cut colour and style!</p></div><div class='ri horizontal-scroll'><div class='rit'><h4>Aurelia F.</h4><p>19 July 2024</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Simply amazing!</p></div><div class='ri horizontal-scroll'><div class='rit'><h4>Chris T.</h4><p>30 July 2024</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Always a fantastic cut and good conversation too!</p></div><div class='ri horizontal-scroll'><div class='rit'><h4>Daria C.</h4><p>31 July 2024</p></div><div class='ristar'><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span><span>&#9733;</span></div><p>Always fantastic service with raisonnables prices. Océane is very flexible and accommodative. Love to come back here every time :)</p></div>";
}

function show() {
    document.querySelector(".show-div").classList.add("s-active");
    console.log("s-active");
}

function idkwhat() {
    document.querySelector(".show-div").classList.remove("s-active");
    console.log("close");
}

